version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      #Tells Kafka how to find Zookeeper 
      #— uses Docker service name zookeeper on port 2181.
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #hostname and port external clients 
      #(like code outside docker that tails log files) use to connect
      #("localhost", instead of "kafka", which is the service name within docker)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  #if running docker-compose up for this individually, use with -d flag
  
  flink-jobmanager:
    image: flink:1.16.1
    container_name: flink-jobmanager
    #exposes webUI ...docker will expose to local machine...http://localhost:8081
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      #task manager will talk to job manager over RPC
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager

  flink-taskmanager:
    image: flink:1.16.1
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      #job manager will talk to task manager over RPC
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
